backend/models/Testimonial.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "node".
 *
 * @property integer $id
 * @property string $title
 * @property string $summary
 * @property string $description
 * @property string $other
 * @property string $image
 * @property string $video
 * @property string $price
 * @property string $link
 * @property string $file
 * @property integer $setting
 * @property string $digit1
 * @property string $digit2
 * @property string $digit3
 * @property string $digit4
 * @property string $digit5
 * @property string $field1
 * @property string $field2
 * @property string $field3
 * @property string $field4
 * @property string $field5
 * @property string $text1
 * @property string $text2
 * @property string $text3
 * @property string $text4
 * @property string $text5
 * @property integer $started_at
 * @property integer $ended_at
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property integer $status
 * @property integer $menu
 * @property string $type
 * @property string $slug
 *
 * @property NodeImage[] $nodeImages
 */
class Testimonial extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $img;
    public static function tableName()
    {
        return 'node';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['summary', 'description', 'other', 'text1', 'text2', 'text3', 'text4', 'text5'], 'string'],
            [['price', 'digit1', 'digit2', 'digit3', 'digit4', 'digit5'], 'number'],
            [['setting', 'started_at', 'ended_at', 'created_at', 'updated_at', 'created_by', 'updated_by', 'status', 'menu'], 'integer'],
            [['title', 'image', 'video', 'link', 'file', 'field1', 'field2', 'field3', 'field4', 'field5', 'type', 'slug'], 'string', 'max' => 255],
            [['title','text2'],'required'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Name',
            'summary' => 'Summary',
            'description' => 'Description',
            'other' => 'Designation',
            'img' => 'Image',
            'video' => 'Video',
            'price' => 'Price',
            'link' => 'Link',
            'file' => 'File',
            'setting' => 'Setting',
            'digit1' => 'Digit1',
            'digit2' => 'Digit2',
            'digit3' => 'Digit3',
            'digit4' => 'Digit4',
            'digit5' => 'Digit5',
            'field1' => 'Field1',
            'field2' => 'Field2',
            'field3' => 'Field3',
            'field4' => 'Field4',
            'field5' => 'Field5',
            'text1' => 'Designation',
            'text2' => 'Company',
            'text3' => 'Text3',
            'text4' => 'Text4',
            'text5' => 'Text5',
            'started_at' => 'Started At',
            'ended_at' => 'Ended At',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'status' => 'Status',
            'menu' => 'Menu',
            'type' => 'Type',
            'slug' => 'Slug',
        ];
    }
    public function behaviors()
    {
      return [
            [
                'class' => 'yii\behaviors\TimestampBehavior',
            ],
            [
                'class' => 'yii\behaviors\SluggableBehavior',
                'attribute' => 'title',
                'ensureUnique'=>true,
                // 'slugAttribute' => 'slug',
            ],
            [
                'class' => 'yii\behaviors\BlameableBehavior',
            ]
      ];
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNodeImages()
    {
        return $this->hasMany(NodeImage::className(), ['nid' => 'id']);
    }
    public function getCreatedBy()
    {
        return $this->hasOne('common\models\User', ['id' => 'created_by']);
    }
    public function getUpdatedBy()
    {
        return $this->hasOne('common\models\User', ['id' => 'updated_by']);
    }
    /**
     * Returns content and replace widgets short codes
     *
     * Widget short code example: [[\app\widgets\SomeWidget:method]]
     *
     * @return string
     */
    public function getContent()
    {
        $content = preg_replace_callback('/\[\[([^(\[\[)]+:[^(\[\[)]+)\]\]/is', [$this, 'replace'], $this->description);
        return $content;
    }
    /**
     * Replaces widget short code on appropriate widget
     *
     * @param $data
     *
     * @return string
     */
    private function replace($data)
    {
        $widget = explode(':', $data[1]);
        if (class_exists($class = $widget[0]) && method_exists($class, $method = $widget[1])) {
            return call_user_func([$class, $method]);
        }
        return '';
    }
    public function getAvatarImage(){
        return yii\helpers\Html::img(Yii::getAlias('@url').'/testimonials/'.$this->image);
    }
    public function getDes()
    {
        if(isset($this->text1) && $this->text2 != NULL)
        return ucwords(preg_replace('/\s+/', '@',$this->text1.' '.$this->text2));
    }
}

frontend/views/widgets/widget--featured.php
<?php
use yii\helpers\Html;
$f1 = true;
$f2 = true;
?>
<div class="row">
<div class="col-lg-3 col-xs-12" data-scrollreveal="enter left over 2s after 0.5s">
<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
<?php foreach ($models as $model):?>
<?php if($f1): $f1 = false; ?>
<a class="nav-link active" id="v-pills-<?=$model->id?>-tab" data-toggle="pill" href="#v-pills-<?=$model->id?>" role="tab" aria-controls="v-pills-home" aria-selected="true"><?=$model->title?></a>
 <?php else: ?>
 <a class="nav-link" id="v-pills-<?=$model->id?>-tab" data-toggle="pill" href="#v-pills-<?=$model->id?>" role="tab" aria-controls="v-pills-home" aria-selected="true"><?=$model->title?></a>
 <?php endif;endforeach;?>
</div>
</div>
<div class="col-lg-9 col-xs-12" data-scrollreveal="enter right over 2s after 0.5s">
<div class="tab-content" id="v-pills-tabContent">
<?php foreach ($models as $model):?>
<?php if($f2): $f2 = false; ?>
<div class="tab-pane fade show active" id="v-pills-<?=$model->id?>" role="tabpanel" aria-labelledby="v-pills-a-tab">
<div class="container">
<div class="row">
<div class="col-sm-12 features-details">
<img src="<?=Yii::$app->imagemanager->getImagePath($model->icon)?>" alt="icon">
<h4><?=$model->title?></h4>
<?=$model->description?>
<?php if(!empty($model->other)) : ?>
<h5>Other details</h5>
<?=$model->other?>
<?php endif;?>
</div>
</div>
</div>
</div>
 <?php else: ?>
<div class="tab-pane fade" id="v-pills-<?=$model->id?>" role="tabpanel" aria-labelledby="v-pills-b-tab">
<div class="container">
<div class="row">
<div class="col-sm-12 features-details">
<img src="<?=Yii::$app->imagemanager->getImagePath($model->icon)?>" alt="icon">
<h4><?=$model->title?></h4>
<?=$model->description?>
<?php if(!empty($model->other)) : ?>
<h5>Other details</h5>
<?=$model->other?>
<?php endif;?>
</div>
</div>
</div>
</div>
<?php endif;endforeach;?>
</div>
</div>
</div>

               

              

            

frontend/views/widgets/widget--promotional.php
<?php
use yii\helpers\Html;
$directoryAsset = Yii::$app->assetManager->getPublishedUrl('@webroot/webassets');
$first = true;
?>
<div class="col-sm-12 app-screen-head">
<img class="dots-head" src="<?=$directoryAsset ?>/images/head-dots.png" alt="dots">
<img src="<?=Yii::$app->imagemanager->getImagePath(Yii::$app->settings->img('logo-body'),275,102)?>" alt="logo">
<p><?=$model->summary?></p>
</div>
<div class="col-sm-12 mobile-splash-screens" data-scrollreveal="enter top over 2s after 0.5s">
<div class="mobile-slider2">
<div id="carouselExampleIndicators2" class="carousel slide carousel-fade" data-ride="carousel">
<div class="carousel-inner d-none d-xl-block d-md-block d-lg-block">
<?php foreach ($model->nodeImages as $image):?>
<?php if($first): $first = false; ?>
<div class="carousel-item active">
<img src="<?=Yii::getAlias('@url/nodeimages/').$image->node_image?>" alt="<?=$image->node_image_title?>">
</div>
<?php else: ?>
<div class="carousel-item">
<img src="<?=Yii::getAlias('@url/nodeimages/').$image->node_image?>" alt="<?=$image->node_image_title?>"></div>
<?php endif; ?>
<?php endforeach; ?>
</div>
<div class="carousel-inner d-md-none d-lg-none d-sm-block">
<div class="col-sm-12 carousel-item active">
<img src="<?=Yii::$app->imagemanager->getImagePath(7,354,453)?>" alt="slides">
</div>
<div class="col-sm-12 carousel-item">
<img src="<?=Yii::$app->imagemanager->getImagePath(8,354,453)?>" alt="slides">
</div>
</div>
</div>
</div>
</div>

frontend/views/widgets/widget--slider.php
<?php
use yii\helpers\Html;
$directoryAsset = Yii::$app->assetManager->getPublishedUrl('@webroot/webassets');
$i = 1;
$first = true;
?>
<div class="col-lg-5 col-sm-12 mobile-slider" data-scrollreveal="enter right over 2s after 0.2s">
<div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
<div class="carousel-inner">
<div class="phn-bg"><img src="<?=$directoryAsset ?>/images/mobile-bg.png" alt="phone"></div>
<?php foreach ($models as $model):?>
<?php if($first): $first = false; ?>
<div class="carousel-item active">
<img src="<?=Yii::getAlias('@url').'/banners/'.$model->image?>" alt="<?=$model->title?>">
</div>
<?php else: ?>
<div class="carousel-item">
<img src="<?=Yii::getAlias('@url').'/banners/'.$model->image?>" alt="<?=$model->title?>">
</div>
<?php endif; ?>
<?php endforeach;?>
</div>
</div>
</div>



               

              

            

frontend/views/widgets/widget--testimonial.php
<?php
use yii\helpers\Html;
?>
<section class="testimonial-area" data-scrollreveal="enter bottom over 2s after 0.5s">
<div class="container custome-width">
<div class="row">
<div class="col-lg-2 col-sm-12 testimonial-title">
<h3><?=Yii::t('*', 'what_people')?></h3>
</div>
<div class="col-lg-10 col-sm-12 testimonial-slider">
<div class="col-sm-12 owl-1 owl-slides no-padding">
<?php foreach ($models as $model):?>  
<div class="item">
<div class="row">
<div class="col-sm-12 profile">
<img src="<?=Yii::getAlias('@url').'/testimonials/'.$model->image?>" alt="profile" class="rounded-circle">
<h4><?=$model->title?></h4>
<h6><?=$model->des?></h6>
<p><?=\yii\helpers\StringHelper::truncate($model->description,120,'...','UTF-8',false)?>
</p>
</div>
</div>
</div>
<?php endforeach;?>
</div>
</div>
</div>
</div>
</section>

               

              

            